spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/gulimall_pms?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s
    nacos:
     discovery:
       server-addr: 127.0.0.1:8848 #nacos注册中心的地址
       #namespace: 1dd1c777-e9fe-497c-8d95-087288702b14
  application:
    name: gulimall-product
  jackson: #格式化事件戳的格式为指定格式
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    #配置redis
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
     
server:
  port: 10001
logging:
  level:
    com.atguigu.gulimall: debug
