---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 张立晨.
--- DateTime: 2022/10/9 10:04
--- 
if redis.call('get', KEYS[1]) == ARGV[1] then
    return redis.call('del', KEYS[1])
else
    return 0
end